apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: leni-app-ui
  name: leni-app-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leni-app-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: leni-app-ui
    spec:
      containers:
      - image: leniaugustine/leni-ui-app:appv1
        name: leni-ui-app
        ports:
        - containerPort: 80
        resources: {}
status: {}
